---
E1:
  hostname: 10.18.10.88
  loopback: 100.64.1.5
  groups:
    - router
  data:
    vrf:
      - vrf_name: CustA
        rd: 111.111.111.111:10
        export: 10:0
        import: 10:0
      - vrf_name: CustZ
        rd: 111.111.111.222:10
        export: 10:0
        import: 10:0
    interfaces:
      - int_name: GigabitEthernet4.20
        vlan_id: 20
        vrf_forwarding: CustA
        ip_address: 192.168.1.69 255.255.255.0
        secondary_ip_address: 192.168.1.42
        priority: 110
    bgp:
      - vrf_name: CustA
        asn: 65000
      - vrf_name: CustB
        asn: 65000  
      
E2:
  hostname: 10.18.10.22
  loopback: 100.64.1.6
  groups:
    - router
  data:
    vrf:
      - vrf_name: vrf2
        rd: 111.111.111.112:10
        export: 10:0
        import: 10:0
      - vrf_name: vrf3
        rd: 111.111.111.223:10
        export: 10:0
        import: 10:0
      - vrf_name: vrf4
        rd: 111.111.234.223:10
        export: 10:0
#E3:
#  hostname: 10.18.10.73
#  loopback: 100.64.1.3
#  groups:
#    - router
#  data: {}
#E4:
#  hostname: 10.18.10.138
#  loopback: 100.64.1.4
#  groups:
#    - router
#  data: {}
