---
ubuntu:
  hostname: 10.18.11.176
  platform: linux
  groups:
    - linux
E1:
  hostname: 10.18.10.88
  loopback: 100.64.1.5
  groups:
    - router
    - edge
    - sideA
E2:
  hostname: 10.18.10.22
  loopback: 100.64.1.6
  groups:
    - router
    - edge
    - sideA
E3:
  hostname: 10.18.10.73
  loopback: 100.64.1.3
  groups:
    - router
    - edge
    - sideB
E4:
  hostname: 10.18.10.138
  loopback: 100.64.1.4
  groups:
    - router
    - edge
    - sideC
C1:
  hostname: 10.18.10.3
  groups:
    - router
    - core
C2:
  hostname: 10.18.10.25
  groups:
    - router
    - core