---
E1:
  hostname: 10.18.10.88
  loopback: 100.64.1.5
  groups:
    - router
  data:
    vrf:
      - vrf_name: CustA
        rd: 192.168.69.69:10
        export: 10:0
        import: 10:0
      - vrf_name: CustB
        rd: 192.168.42.42:20
        export: 20:0
        import: 20:0
    interfaces:
      - int_name: GigabitEthernet4.10
        vlan_id: 10
        vrf_forwarding: CustA
        ip_address: 192.168.1.1 255.255.255.0
        secondary_ip_address: 192.168.1.42
        priority: 110
      - int_name: GigabitEthernet4.20
        vlan_id: 20
        vrf_forwarding: CustB
        ip_address: 192.168.21.2 255.255.255.0
        secondary_ip_address: 192.168.21.42
        priority: 110
    bgp:
      - vrf_name: CustA
        asn: 65000
      - vrf_name: CustB
        asn: 65000  
      
E2:
  hostname: 10.18.10.22
  loopback: 100.64.1.6
  groups:
    - router
  data:
    data:
    vrf:
      - vrf_name: CustA
        rd: 192.168.69.69:10
        export: 10:0
        import: 10:0
      - vrf_name: CustB
        rd: 192.168.42.42:20
        export: 20:0
        import: 20:0
    interfaces:
      - int_name: GigabitEthernet4.10
        vlan_id: 10
        vrf_forwarding: CustA
        ip_address: 192.168.1.1 255.255.255.0
        secondary_ip_address: 192.168.1.42
        priority: 110
      - int_name: GigabitEthernet4.20
        vlan_id: 20
        vrf_forwarding: CustB
        ip_address: 192.168.21.2 255.255.255.0
        secondary_ip_address: 192.168.21.42
        priority: 110
    bgp:
      - vrf_name: CustA
        asn: 65000
      - vrf_name: CustB
        asn: 65000
E3:
  hostname: 10.18.10.73
  loopback: 100.64.1.3
  groups:
    - router
  data:
    vrf:
      - vrf_name: CustA
        rd: 192.168.69.69:10
        export: 10:0
        import: 10:0
    interfaces:
      - int_name: GigabitEthernet4
        vlan_id: 10
        vrf_forwarding: CustA
        ip_address: 192.168.2.1 255.255.255.0
        secondary_ip_address: 192.168.1.43
        priority: 110
    bgp:
      - vrf_name: CustA
        asn: 65000
E4:
  hostname: 10.18.10.138
  loopback: 100.64.1.4
  groups:
    - router
  data:
    vrf:
      - vrf_name: CustA
        rd: 192.168.69.69:10
        export: 10:0
        import: 10:0
    interfaces:
      - int_name: GigabitEthernet4
        vlan_id: 10
        vrf_forwarding: CustA
        ip_address: 192.168.3.1 255.255.255.0
        secondary_ip_address: 192.168.1.44
        priority: 110
    bgp:
      - vrf_name: CustA
        asn: 65000
